### ISSUE TITLE
留言

### ISSUE THREAD

**Issue by zltf** [TheZihanGu/php-biaoqingbao-gif#1]
你好，今天我收到一条百度智能云的短信。
内容是这样的：
【百度智能云】尊敬的用户，经检测有如下已备案但未在百度云接入的域名（zihangu.com）指向了您购买的百度云IP，请您尽快登录百度云备案系统（beian.bce.baidu.com）完成备案接入业务，以免影响网站服务，请您知晓并关注。如有疑惑请通过百度云工单系统或致电4008-777-818咨询，感谢您的理解与支持！
请你检查有没有将ip指向有没有错误。

**Comment by TheZihanGu** [comment]
已检查并核实，感谢提醒。
